debug: true
server:
  port: 8080
spring:
  devtools:
    restart:
        enabled: true
    livereload:
        enabled: false
  jpa:
    database: POSTGRESQL
  datasource:
    platform: postgres
    url: jdbc:postgresql://192.168.56.50/ucims
    driverClassName: org.postgresql.Driver
    username: ucims
    password: ucims
  data:
    elasticsearch:
      cluster-name:
      cluster-nodes: "192.168.56.50:9300"

